name: Deploy Fullstack App on EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ------------------------------
      # BACKEND SETUP
      # ------------------------------
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Create backend .env file
        working-directory: backend
        run: |
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Start backend with PM2
        working-directory: backend
        run: |
          pm2 restart backend || pm2 start index.js --name backend
          pm2 save

      # ------------------------------
      # FRONTEND SETUP
      # ------------------------------
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Create frontend .env file
        working-directory: frontend
        run: |
          echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy frontend to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r frontend/dist/* /var/www/html/
